apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    example.dev/release: "v0.0.1"
  name: crd1.example.dev
spec:
  group: example.dev
  names:
    kind: CRD1
    plural: crd1s
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
  - name: v1
    served: true
    storage: false

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    example.dev/release: "v0.0.1"
  name: crd2.example.dev
spec:
  group: example.dev
  names:
    kind: CRD2
    plural: crd2s
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
  - name: v1
    served: true
    storage: false
