/*
Copyright 2019 JD Cloud

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/sky-big/kubernetes-crd-controller/pkg/apis/example/v1alpha1"
	scheme "github.com/sky-big/kubernetes-crd-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CRD1sGetter has a method to return a CRD1Interface.
// A group's client should implement this interface.
type CRD1sGetter interface {
	CRD1s(namespace string) CRD1Interface
}

// CRD1Interface has methods to work with CRD1 resources.
type CRD1Interface interface {
	Create(*v1alpha1.CRD1) (*v1alpha1.CRD1, error)
	Update(*v1alpha1.CRD1) (*v1alpha1.CRD1, error)
	UpdateStatus(*v1alpha1.CRD1) (*v1alpha1.CRD1, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.CRD1, error)
	List(opts v1.ListOptions) (*v1alpha1.CRD1List, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CRD1, err error)
	CRD1Expansion
}

// cRD1s implements CRD1Interface
type cRD1s struct {
	client rest.Interface
	ns     string
}

// newCRD1s returns a CRD1s
func newCRD1s(c *ExampleV1alpha1Client, namespace string) *cRD1s {
	return &cRD1s{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the cRD1, and returns the corresponding cRD1 object, and an error if there is any.
func (c *cRD1s) Get(name string, options v1.GetOptions) (result *v1alpha1.CRD1, err error) {
	result = &v1alpha1.CRD1{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("crd1s").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CRD1s that match those selectors.
func (c *cRD1s) List(opts v1.ListOptions) (result *v1alpha1.CRD1List, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.CRD1List{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("crd1s").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested cRD1s.
func (c *cRD1s) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("crd1s").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a cRD1 and creates it.  Returns the server's representation of the cRD1, and an error, if there is any.
func (c *cRD1s) Create(cRD1 *v1alpha1.CRD1) (result *v1alpha1.CRD1, err error) {
	result = &v1alpha1.CRD1{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("crd1s").
		Body(cRD1).
		Do().
		Into(result)
	return
}

// Update takes the representation of a cRD1 and updates it. Returns the server's representation of the cRD1, and an error, if there is any.
func (c *cRD1s) Update(cRD1 *v1alpha1.CRD1) (result *v1alpha1.CRD1, err error) {
	result = &v1alpha1.CRD1{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("crd1s").
		Name(cRD1.Name).
		Body(cRD1).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *cRD1s) UpdateStatus(cRD1 *v1alpha1.CRD1) (result *v1alpha1.CRD1, err error) {
	result = &v1alpha1.CRD1{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("crd1s").
		Name(cRD1.Name).
		SubResource("status").
		Body(cRD1).
		Do().
		Into(result)
	return
}

// Delete takes name of the cRD1 and deletes it. Returns an error if one occurs.
func (c *cRD1s) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("crd1s").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *cRD1s) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("crd1s").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched cRD1.
func (c *cRD1s) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CRD1, err error) {
	result = &v1alpha1.CRD1{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("crd1s").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
