apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-crd-controller

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kubernetes-crd-controller
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - "*"

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kubernetes-crd-controller-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: kubernetes-crd-controller
  namespace: default
roleRef:
  kind: ClusterRole
  name: kubernetes-crd-controller
  apiGroup: rbac.authorization.k8s.io