/*
Copyright 2019 JD Cloud

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/sky-big/kubernetes-crd-controller/pkg/apis/example/v1"
	scheme "github.com/sky-big/kubernetes-crd-controller/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CRD2sGetter has a method to return a CRD2Interface.
// A group's client should implement this interface.
type CRD2sGetter interface {
	CRD2s(namespace string) CRD2Interface
}

// CRD2Interface has methods to work with CRD2 resources.
type CRD2Interface interface {
	Create(*v1.CRD2) (*v1.CRD2, error)
	Update(*v1.CRD2) (*v1.CRD2, error)
	UpdateStatus(*v1.CRD2) (*v1.CRD2, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.CRD2, error)
	List(opts metav1.ListOptions) (*v1.CRD2List, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.CRD2, err error)
	CRD2Expansion
}

// cRD2s implements CRD2Interface
type cRD2s struct {
	client rest.Interface
	ns     string
}

// newCRD2s returns a CRD2s
func newCRD2s(c *ExampleV1Client, namespace string) *cRD2s {
	return &cRD2s{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the cRD2, and returns the corresponding cRD2 object, and an error if there is any.
func (c *cRD2s) Get(name string, options metav1.GetOptions) (result *v1.CRD2, err error) {
	result = &v1.CRD2{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("crd2s").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CRD2s that match those selectors.
func (c *cRD2s) List(opts metav1.ListOptions) (result *v1.CRD2List, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.CRD2List{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("crd2s").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested cRD2s.
func (c *cRD2s) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("crd2s").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a cRD2 and creates it.  Returns the server's representation of the cRD2, and an error, if there is any.
func (c *cRD2s) Create(cRD2 *v1.CRD2) (result *v1.CRD2, err error) {
	result = &v1.CRD2{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("crd2s").
		Body(cRD2).
		Do().
		Into(result)
	return
}

// Update takes the representation of a cRD2 and updates it. Returns the server's representation of the cRD2, and an error, if there is any.
func (c *cRD2s) Update(cRD2 *v1.CRD2) (result *v1.CRD2, err error) {
	result = &v1.CRD2{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("crd2s").
		Name(cRD2.Name).
		Body(cRD2).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *cRD2s) UpdateStatus(cRD2 *v1.CRD2) (result *v1.CRD2, err error) {
	result = &v1.CRD2{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("crd2s").
		Name(cRD2.Name).
		SubResource("status").
		Body(cRD2).
		Do().
		Into(result)
	return
}

// Delete takes name of the cRD2 and deletes it. Returns an error if one occurs.
func (c *cRD2s) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("crd2s").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *cRD2s) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("crd2s").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched cRD2.
func (c *cRD2s) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.CRD2, err error) {
	result = &v1.CRD2{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("crd2s").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
